name: GitHub Actions
run-name: Pipeline 🚀
on:
  pull_request:
  push:
    branches:
      - main
    path-ignore:
      - '.github/workflows/*'
jobs:
  build:
    strategy:
      matrix:
        node-version: [17.x]
        os: [ubuntu-latest]
        command: [npm run build, npm run lint]
    runs-on: ${{matrix.os}}
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{hashfiles('**/package-lock.json')}}
      - name: install modules
        run: npm ci
      - name: build project
        run: ${{matrix.command}}
